-- tools/run.sh tools/buildintuition.lua <records.lua> [<records.lua> ...] [--out Data/Intuition_TBC.lua]
--
-- Merge many imported fights into ONE blurred prior and write it as a shipped
-- data file (docs/SPEC-v0.13.md §11). The point is breadth: a dozen different
-- encounters across four raids, folded together and quantised, so what survives
-- is "a tank takes about this much, a damager about that much, and it opens
-- harder than it sustains" -- experience, not a lookup table.
--
-- Rates are FRACTIONS OF MAX HEALTH per second, which is the only form in which
-- somebody else's Sunwell raid says anything useful about your Hellfire pull.
local here = arg[0]:match("^(.*)/[^/]+$")
local files, out = {}, "Data/Intuition_TBC.lua"
do
    -- tools/run.sh passes the checkout root as arg[1]; the caller's own
    -- arguments start at 2 (the other tools get away with i=1 only because
    -- their parsers happen to reject a path)
    local i = 2
    while i <= #arg do
        if arg[i] == "--out" then out = arg[i + 1]; i = i + 1
        else files[#files + 1] = arg[i] end
        i = i + 1
    end
end
if #files == 0 then print("usage: buildintuition.lua <records.lua> ..."); os.exit(2) end

local recs, sources = {}, {}
for _, f in ipairs(files) do
    _G.SpellTunerDB, _G.ManaDemonDB = nil, nil
    dofile(f)
    local db = _G.SpellTunerDB or _G.ManaDemonDB
    for key, c in pairs((db or {}).char or {}) do
        for _, rec in ipairs(c.recordings or {}) do
            recs[#recs + 1] = rec
            sources[#sources + 1] = string.format("%s (%s)", tostring(rec.zone), key)
        end
    end
end
_G.SpellTunerDB, _G.ManaDemonDB = nil, nil

local a0 = arg[0]; arg[0] = here .. "/harness.lua"
local MD = dofile(here .. "/harness.lua"); arg[0] = a0
local IN = MD.Intuition

local prior = IN:Build(recs, nil)
local blurred = IN:Blur(prior, 0.005)
print(string.format("%d recording(s) -> %s", #recs, IN:Describe(blurred)))

-- what the corpus covers, for the file's own provenance
local zones, encs = {}, {}
for _, rec in ipairs(recs) do
    local z = rec.encounter or tostring(rec.zone):match("^([^%(]+)") or tostring(rec.zone)
    z = (z:gsub("%s+$", ""))
    encs[z] = true
    zones[z] = (zones[z] or 0) + 1
end
local nEnc = 0
for _ in pairs(encs) do nEnc = nEnc + 1 end

local function fmt(v) return string.format("%.4f", v or 0) end
local lines = {}
local function w(s) lines[#lines + 1] = s end
w("local _, MD = ...")
w("")
w("--------------------------------------------------------------------------------")
w("-- Shipped healer intuition (docs/SPEC-v0.13.md §11). GENERATED by")
w("-- tools/buildintuition.lua from imported Warcraft Logs fights -- do not hand")
w("-- edit; rebuild it.")
w("--")
w("-- Rates are FRACTIONS OF MAX HEALTH PER SECOND, blurred to the nearest 0.5%,")
w("-- because a number read off this file is not a fact about anybody's next pull.")
w("-- `open` is the first 10 seconds, `rest` the remainder, `spread` the ratio")
w("-- between the busiest and quietest fight in the corpus for that role -- a role")
w("-- that swings by five times between encounters is not worth believing much.")
w("--")
w(string.format("-- Built %s from %d fight(s) across %d encounter(s).",
    os.date("%Y-%m-%d"), #recs, nEnc))
for z, n in pairs(zones) do w(string.format("--   %-46s %d", z, n)) end
w("--------------------------------------------------------------------------------")
w("")
w("MD.IntuitionTBC = {")
w(string.format("    version = 1, built = %q, fights = %d, encounters = %d,",
    os.date("%Y-%m-%d"), #recs, nEnc))
w(string.format("    blurred = %s,", fmt(blurred.blurred)))
w("    source = \"Warcraft Logs, TBC Anniversary (fresh)\",")
w("    all = {")
for _, role in ipairs({ "TANK", "HEALER", "DAMAGER" }) do
    local r = blurred.all and blurred.all[role]
    if r then
        w(string.format("        %s = { open = %s, rest = %s, n = %d%s },",
            role, fmt(r.open), fmt(r.rest), r.n or 0,
            r.spread and string.format(", spread = %.1f", r.spread) or ""))
    end
end
w("    },")
w("    zones = {")
for zone, roles in pairs(blurred.zones or {}) do
    local any = false
    for _, r in pairs(roles) do if (r.n or 0) >= 2 then any = true end end
    if any then
        w(string.format("        [%q] = {", zone))
        for _, role in ipairs({ "TANK", "HEALER", "DAMAGER" }) do
            local r = roles[role]
            if r and (r.n or 0) >= 2 then
                w(string.format("            %s = { open = %s, rest = %s, n = %d },",
                    role, fmt(r.open), fmt(r.rest), r.n))
            end
        end
        w("        },")
    end
end
w("    },")
w("}")
w("")

local f = assert(io.open(out, "w"))
f:write(table.concat(lines, "\n"))
f:close()
print("wrote " .. out .. " (" .. #lines .. " lines)")
